name: gonews
description: India ki Awaaz - Your trusted source for Indian news
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  go_router: ^13.2.0
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Network & HTTP
  dio: ^5.4.0
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  
  # UI Components
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  
  # Utilities
  share_plus: ^7.2.2
  url_launcher: ^6.2.2
  intl: ^0.19.0
  
  # Authentication (for Phase 2)
  google_sign_in: ^6.2.1
  
  # Icons & Fonts
  cupertino_icons: ^1.0.6

  # JSON Handling
  json_annotation: ^4.8.1

  # Secure Storage (optional for enhanced token security)
  flutter_secure_storage: ^9.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  freezed: ^2.4.7
  json_serializable: ^6.7.1 # JSON Code Generation
  
  # Analysis
  flutter_lints: ^3.0.0
  very_good_analysis: ^5.1.0

  # QR Code Generation (for Phase 3)
  qr_flutter: ^4.1.0

  


flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/images/
  #   - assets/icons/
  
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700