name: gonews
description: India ki Awaaz - Your trusted source for Indian news
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  go_router: ^13.2.0
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Network & HTTP
  dio: ^5.4.0
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  
  # UI Components
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  
  # Utilities
  share_plus: ^7.2.2
  url_launcher: ^6.2.2
  intl: ^0.19.0
  
  # Authentication
  google_sign_in: ^6.2.1
  
  # Icons & Fonts
  cupertino_icons: ^1.0.6

  # JSON Handling
  json_annotation: ^4.8.1

  # Secure Storage
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  
  # Analysis
  flutter_lints: ^3.0.0
  very_good_analysis: ^5.1.0

  # App Icon Generation
  flutter_launcher_icons: ^0.13.1

  # QR Code Generation (for Phase 3)
  qr_flutter: ^4.1.0

# App Icon Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/gonews_logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/gonews_logo.png"
    background_color: "#FF6B35"
    theme_color: "#FF6B35"
  windows:
    generate: true
    image_path: "assets/icons/gonews_logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/gonews_logo.png"

flutter:
  uses-material-design: true
  
  # Assets Configuration
  assets:
    - assets/icons/
    - assets/fallback_images/politics/
    - assets/fallback_images/business/
    - assets/fallback_images/sports/
    - assets/fallback_images/technology/
    - assets/fallback_images/health/
   # - assets/fallback_images/breaking 
    #- assets/fallback_images/defence 
   # - assets/fallback_images/education
    #- assets/fallback_images/entertainment/
    #- assets/fallback_images/general/
    #- assets/fallback_images/international/
    #- assets/fallback_images/regional/
    #- assets/fallback_images/science/
    #- assets/fallback_images/top-stories/